---
title: "Meteorology Summary for NY State (2016 - 2020)"
site: false
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
resource_files:
  - data/NYcounty_fips/*
  - data/meteor_2016to20_NY.csv
---

```{r setup}
library(flexdashboard)
library(leaflet)
library(mapview)
library(plotly)
library(sf)
library(tidyverse)
library(shiny)
library(viridis)
```

```{r data import, message = FALSE}
NYcounty <- sf::read_sf("data/NYcounty_fips/NYcounty_fips.shp") 

meteor_r <- read_csv("data/meteor_2016to20_NY.csv") |>
  mutate(
    year = year(date),
    tmmn_c = tmmn - 273.15,
    tmmx_c = tmmx - 273.15,
    fips = as.character(fips)
  ) |>
  select(-tmmn, -tmmx, -th, -county) |>
  select(fips, year, date, everything()) |>
  pivot_longer(
    cols = c("sph": "tmmx_c"),
    names_to = "var",
    values_to = "value"
  ) |>
  mutate(
    var = as.character(var),
    var.char = case_when(
      var == "sph" ~ "near-surface specific humidity",
      var == "vpd" ~ "vapor pressure deficit (kPa)",
      var == "tmmn_c" ~ "minimum near-surface air temperature (C)",
      var == "tmmx_c" ~ "maximum near-surface air temperature (C)",
      var == "pr" ~ "precipitation (mm, daily total)",
      var == "rmin" ~ "minimum near-surface relative humidity (%)",
      var == "rmax" ~ "maximum near-surface relative humidity (%)",
      var == "srad" ~ "surface downwelling solar radiation (W/m^2)",
      var == "vs" ~ "wind speed at 10m (m/s)",
      TRUE ~ NA_character_
    ),
    var.char = str_to_title(var.char)
  )

meteor_summ_yr = meteor_r |>
  group_by(year, fips, var, var.char) |>
  summarise(
    mean_value = mean(value),
    .groups = "drop"
  )
```

Filters {.sidebar}
-----------------------------------------------------------------------

```{r var_choice}

vars = meteor_summ_yr |> distinct(var.char) |> pull()

radioButtons(
  inputId = "var_choice",
  label = h3("Meteorological Variables"),
  choices = vars,
  selected = "Maximum Near-Surface Air Temperature (C)"
)
```

```{r}
min_year = meteor_summ_yr |> distinct(year) |> min()  # 2016
max_year = meteor_summ_yr |> distinct(year) |> max()  # 2020

sliderInput(
  inputId = "yr_range", 
  label = h3("Choose Year Range"),
  min = min_year,
  max = max_year,
  value = c(min_year, max_year)
)
```

Column {data-width=550}
-----------------------------------------------------------------------
### Mean Meteorological Values by county in NY state within the chosen years

```{r}
renderPlotly({

  meteor_sf = meteor_summ_yr |>
    filter(
      var.char == input[["var_choice"]],
      year >= input[["yr_range"]][1],
      year <= input[["yr_range"]][2]
    ) |> 
    group_by(fips) |>
    summarise(
      mean_value = mean(mean_value)
    ) |>
    left_join(NYcounty, by = "fips") |>
    st_as_sf()
  
  ggplotly(
    ggplot(meteor_sf, color = rgb(0.95, 0.95, 0.95, alpha = 0.3), size = 0.1) +
    geom_sf(aes(fill = mean_value), alpha = 0.8) +
    scale_fill_viridis_c(
      name = NULL,
      option = if_else(
          str_detect(input[["var_choice"]], "Max|Solar"), 
          "plasma", 
          "mako"
        ),
      na.value = "grey80"
    ) +
    labs(
      x = NULL,
      y = NULL
  ) +
  theme_minimal() +
    theme(
      plot.title = element_text(
        hjust = 0.5,
        margin = margin(b = 5)
      )
    )
  )
})
```

Column {data-width=450}
-----------------------------------------------------------------------
### Mean Meteorological Values across NY state for each day within the chosen years

```{r}
renderPlotly({

  meteor_r |>
    filter(
      var.char == input[["var_choice"]],
      year >= input[["yr_range"]][1],
      year <= input[["yr_range"]][2]
    ) |> 
    group_by(var.char, date) |>
    summarise(
      mean_value = mean(value)
    ) |>

    plot_ly(
      x = ~date, 
      y = ~mean_value,
      color = ~mean_value,
      type = "scatter",
      mode = "markers",
      alpha = 0.5
    ) |>
    layout(
      xaxis = list(
        range = c(
          as_date(str_c(input[["yr_range"]][1], "-01-01")),
          as_date(str_c(input[["yr_range"]][2], "-12-31"))
        )
      )
    )
})
```


### Chart C

```{r}

```
